### Analysis of Factors Predicting User Adoption

Objective

The goal of this analysis is to identify which factors predict whether a user will adopt the product. Adoption is defined according to the product team’s criteria, and features were computed using user activity, account creation metadata, and engagement flags.

### Import libraries

In [163]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, roc_auc_score

#### Read data files

In [164]:
users = pd.read_csv('../takehome_users.csv', encoding="ISO-8859-1")
engagements = pd.read_csv('../takehome_user_engagement.csv', encoding="ISO-8859-1")

In [165]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   object_id                   12000 non-null  int64
 1   creation_time               12000 non-null  object
 2   name                        12000 non-null  object
 3   email                       12000 non-null  object
 4   creation_source             12000 non-null  object
 5   last_session_creation_time  8823 non-null   float64
 6   opted_in_to_mailing_list    12000 non-null  int64
 7   enabled_for_marketing_drip  12000 non-null  int64
 8   org_id                      12000 non-null  int64
 9   invited_by_user_id          6417 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 937.6+ KB

In [166]:
engagements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207917 entries, 0 to 207916
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   time_stamp  207917 non-null  object
 1   user_id     207917 non-null  int64
 2   visited     207917 non-null  int64
dtypes: int64(2), object(1)
memory usage: 4.8+ MB

In [167]:
# Extract date from login timestamps
# timestamp -> login date
engagements['time_stamp'] = pd.to_datetime(engagements['time_stamp'])
engagements['login_date'] = pd.to_datetime(engagements['time_stamp'].dt.date)

In [168]:
engagements.head()

           time_stamp  user_id  visited login_date
0 2014-04-22 03:53:30        1        1 2014-04-22
1 2013-11-15 03:45:04        2        1 2013-11-15
2 2013-11-29 03:45:04        2        1 2013-11-29
3 2013-12-09 03:45:04        2        1 2013-12-09
4 2013-12-25 03:45:04        2        1 2013-12-25

In [169]:
# Get creation time
# creation time from 'users'
engagement_sessions = engagements.merge(users[['object_id', 'creation_time']], left_on='user_id', right_on='object_id', how='left')

# Normalize creation date and login date
# creation_time -> creation_date
engagement_sessions['creation_date'] = pd.to_datetime(engagement_sessions['creation_time']).dt.normalize()
engagement_sessions['login_date'] = engagement_sessions['login_date'].dt.normalize()
engagement_sessions.drop(columns=['visited', 'object_id', 'creation_time'], inplace=True)

In [170]:
# days since user created
full_sessions = engagement_sessions.copy()
full_sessions['days_since_creation'] = (full_sessions['login_date'] - full_sessions['creation_date']).dt.days
full_sessions.head(20)

            time_stamp  user_id login_date creation_date  days_since_creation
0  2014-04-22 03:53:30        1 2014-04-22    2014-04-22                    0
1  2013-11-15 03:45:04        2 2013-11-15    2013-11-15                    0
2  2013-11-29 03:45:04        2 2013-11-29    2013-11-15                   14
3  2013-12-09 03:45:04        2 2013-12-09    2013-11-15                   24
4  2013-12-25 03:45:04        2 2013-12-25    2013-11-15                   40
5  2013-12-31 03:45:04        2 2013-12-31    2013-11-15                   46
6  2014-01-08 03:45:04        2 2014-01-08    2013-11-15                   54
7  2014-02-03 03:45:04        2 2014-02-03    2013-11-15                   80
8  2014-02-08 03:45:04        2 2014-02-08    2013-11-15                   85
9  2014-02-09 03:45:04        2 2014-02-09    2013-11-15                   86
10 2014-02-13 03:45:04        2 2014-02-13    2013-11-15                   90
11 2014-02-16 03:45:04        2 2014-02-16    2013-11-15                   93
12 2014-03-09 03:45:04        2 2014-03-09    2013-11-15                  114
13 2014-03-13 03:45:04        2 2014-03-13    2013-11-15                  118
14 2014-03-31 03:45:04        2 2014-03-31    2013-11-15                  136
15 2013-03-19 23:14:52        3 2013-03-19    2013-03-19                    0
16 2013-05-22 08:09:28        4 2013-05-22    2013-05-21                    1
17 2013-01-22 10:14:20        5 2013-01-22    2013-01-17                    5
18 2013-12-19 03:37:06        6 2013-12-19    2013-12-17                    2
19 2012-12-20 13:24:32        7 2012-12-20    2012-12-16                    4

#### Target leakage
To avoid leakage in feature engineering, first 14 days counts should be pre-adoption for adopted users

In [171]:
# only need one session per day per user
# each user -> one login day count
user_sessions = full_sessions.drop_duplicates(['user_id', 'login_date'])
user_sessions = user_sessions.sort_values(['user_id', 'login_date'])
user_sessions.head(10)

           time_stamp  user_id login_date creation_date  days_since_creation
0 2014-04-22 03:53:30        1 2014-04-22    2014-04-22                    0
1 2013-11-15 03:45:04        2 2013-11-15    2013-11-15                    0
2 2013-11-29 03:45:04        2 2013-11-29    2013-11-15                   14
3 2013-12-09 03:45:04        2 2013-12-09    2013-11-15                   24
4 2013-12-25 03:45:04        2 2013-12-25    2013-11-15                   40
5 2013-12-31 03:45:04        2 2013-12-31    2013-11-15                   46
6 2014-01-08 03:45:04        2 2014-01-08    2013-11-15                   54
7 2014-02-03 03:45:04        2 2014-02-03    2013-11-15                   80
8 2014-02-08 03:45:04        2 2014-02-08    2013-11-15                   85
9 2014-02-09 03:45:04        2 2014-02-09    2013-11-15                   86

In [172]:
# Find start of current window date - 2 logins back
# user login date -> window start, two logins before
user_sessions['window_start_date'] = user_sessions.groupby('user_id').login_date.shift(2)
user_sessions.head(10)

,time_stamp,user_id,login_date,creation_date,days_since_creation,window_start_date
0,2014-04-22 03:53:30,1,2014-04-22,2014-04-22,0,NaT
1,2013-11-15 03:45:04,2,2013-11-15,2013-11-15,0,NaT
2,2013-11-29 03:45:04,2,2013-11-29,2013-11-15,14,NaT
3,2013-12-09 03:45:04,2,2013-12-09,2013-11-15,24,2013-11-15
4,2013-12-25 03:45:04,2,2013-12-25,2013-11-15,40,2013-11-29
5,2013-12-31 03:45:04,2,2013-12-31,2013-11-15,46,2013-12-09
6,2014-01-08 03:45:04,2,2014-01-08,2013-11-15,54,2013-12-25
7,2014-02-03 03:45:04,2,2014-02-03,2013-11-15,80,2013-12-31
8,2014-02-08 03:45:04,2,2014-02-08,2013-11-15,85,2014-01-08
9,2014-02-09 03:45:04,2,2014-02-09,2013-11-15,86,2014-02-03

In [173]:
# Days occupying window (adoption criteria, must be < 7)
# days between window_start_date and login_date
user_sessions['days_in_window'] = (user_sessions['login_date'] - user_sessions['window_start_date']).dt.days
user_sessions.shape

(207917, 7)

In [174]:
# Mark users adopted if window occupies less than or equal to 6 days
# Identify users who reached adoption
# if number of days in window <= 6, adopted
adopted_users = user_sessions[user_sessions['days_in_window'] <= 6]['user_id'].unique()

# Filter only adopted users
# adopted users login sessions per day
adopted_user_sessions = user_sessions[user_sessions['user_id'].isin(adopted_users)].copy()

# For each adopted user, find the first window where days_in_window <= 6
# first qualifying adopted window, use login_date as adoption_cutoff_date
adoption_cutoff = (adopted_user_sessions[adopted_user_sessions['days_in_window'] <= 6].groupby('user_id')['login_date'].first()
    .rename('adoption_cutoff_date')
    .reset_index()
)

# Merge cutoff back to all sessions (so non-adopted users will have NaT)
sessions_with_cutoff = full_sessions.merge(adoption_cutoff, on='user_id', how='left')
sessions_with_cutoff.head(10)

,time_stamp,user_id,login_date,creation_date,days_since_creation,adoption_cutoff_date
0,2014-04-22 03:53:30,1,2014-04-22,2014-04-22,0,NaT
1,2013-11-15 03:45:04,2,2013-11-15,2013-11-15,0,2014-02-09
2,2013-11-29 03:45:04,2,2013-11-29,2013-11-15,14,2014-02-09
3,2013-12-09 03:45:04,2,2013-12-09,2013-11-15,24,2014-02-09
4,2013-12-25 03:45:04,2,2013-12-25,2013-11-15,40,2014-02-09
5,2013-12-31 03:45:04,2,2013-12-31,2013-11-15,46,2014-02-09
6,2014-01-08 03:45:04,2,2014-01-08,2013-11-15,54,2014-02-09
7,2014-02-03 03:45:04,2,2014-02-03,2013-11-15,80,2014-02-09
8,2014-02-08 03:45:04,2,2014-02-08,2013-11-15,85,2014-02-09
9,2014-02-09 03:45:04,2,2014-02-09,2013-11-15,86,2014-02-09

In [175]:
# Keep sessions only before adoption cutoff for adopted users
# session up until adoption_cutoff_date
sessions_with_cutoff = sessions_with_cutoff[(sessions_with_cutoff['adoption_cutoff_date'].isna()) | 
                                                       (sessions_with_cutoff['login_date'] <= sessions_with_cutoff['adoption_cutoff_date'])]
sessions_with_cutoff.head(20)

,time_stamp,user_id,login_date,creation_date,days_since_creation,adoption_cutoff_date
0,2014-04-22 03:53:30,1,2014-04-22,2014-04-22,0,NaT
1,2013-11-15 03:45:04,2,2013-11-15,2013-11-15,0,2014-02-09
2,2013-11-29 03:45:04,2,2013-11-29,2013-11-15,14,2014-02-09
3,2013-12-09 03:45:04,2,2013-12-09,2013-11-15,24,2014-02-09
4,2013-12-25 03:45:04,2,2013-12-25,2013-11-15,40,2014-02-09
5,2013-12-31 03:45:04,2,2013-12-31,2013-11-15,46,2014-02-09
6,2014-01-08 03:45:04,2,2014-01-08,2013-11-15,54,2014-02-09
7,2014-02-03 03:45:04,2,2014-02-03,2013-11-15,80,2014-02-09
8,2014-02-08 03:45:04,2,2014-02-08,2013-11-15,85,2014-02-09
9,2014-02-09 03:45:04,2,2014-02-09,2013-11-15,86,2014-02-09
15,2013-03-19 23:14:52,3,2013-03-19,2013-03-19,0,NaT
16,2013-05-22 08:09:28,4,2013-05-22,2013-05-21,1,NaT
17,2013-01-22 10:14:20,5,2013-01-22,2013-01-17,5,NaT
18,2013-12-19 03:37:06,6,2013-12-19,2013-12-17,2,NaT
19,2012-12-20 13:24:32,7,2012-12-20,2012-12-16,4,NaT
20,2013-01-16 22:08:03,10,2013-01-16,2013-01-16,0,2013-02-19
21,2013-01-22 22:08:03,10,2013-01-22,2013-01-16,6,2013-02-19
22,2013-01-30 22:08:03,10,2013-01-30,2013-01-16,14,2013-02-19
23,2013-02-04 22:08:03,10,2013-02-04,2013-01-16,19,2013-02-19
24,2013-02-06 22:08:03,10,2013-02-06,2013-01-16,21,2013-02-19

In [176]:
(sessions_with_cutoff['login_date'] > sessions_with_cutoff['adoption_cutoff_date']).sum()

0

### Aggregate features

In [177]:
# sessions in the first 14 days
first_14_days_sessions = sessions_with_cutoff[sessions_with_cutoff['days_since_creation'] < 14]

- active_days_first_14_days: Measures early engagement consistency

In [178]:
# Active days in first 14 days
# unique days per user in first 14 days
active_days_first_14 = first_14_days_sessions.groupby('user_id')['login_date'].nunique().rename('active_days_first_14_days').reset_index()
active_days_first_14.head(15)

    user_id  active_days_first_14_days
0         1                          1
1         2                          1
2         3                          1
3         4                          1
4         5                          1
5         6                          1
6         7                          1
7        10                          2
8        11                          1
9        13                          1
10       14                          1
11       17                          1
12       19                          2
13       20                          3
14       21                          1

- days_active_before_adoption: number of days before adoption

In [179]:
# Count unique days per user
days_active_before_adoption = sessions_with_cutoff.groupby('user_id')['login_date'].nunique().rename('days_active_before_adoption').reset_index()
days_active_before_adoption.head(15)

    user_id  days_active_before_adoption
0         1                            1
1         2                            9
2         3                            1
3         4                            1
4         5                            1
5         6                            1
6         7                            1
7        10                            8
8        11                            1
9        13                            1
10       14                            1
11       17                            1
12       19                            2
13       20                            3
14       21                            1

- days_since_creation_before_adoption: maximum days_since_creation before adoption cutoff

In [180]:
days_since_creation_before_adoption = sessions_with_cutoff.groupby('user_id')['days_since_creation'].max()\
                                                          .rename('days_since_creation_before_adoption').reset_index()

days_since_creation_before_adoption.head(15)

    user_id  days_since_creation_before_adoption
0         1                                    0
1         2                                   86
2         3                                    0
3         4                                    1
4         5                                    5
5         6                                    2
6         7                                    4
7        10                                   34
8        11                                    1
9        13                                    0
10       14                                    1
11       17                                    3
12       19                                    6
13       20                                    7
14       21                                    0

### Target label
Calculated adopted users above, I just add flag if they are adopted

In [181]:
# Create a user-level DataFrame with adopted flag
adopted_flag_df = pd.DataFrame({'user_id': user_sessions['user_id'].unique()})
adopted_flag_df['adopted'] = adopted_flag_df['user_id'].isin(adopted_users).astype(int)

adopted_flag_df.head()

   user_id  adopted
0        1        0
1        2        1
2        3        0
3        4        0
4        5        0

### Retrieve any info from users df

In [182]:
users.columns

Index(['object_id', 'creation_time', 'name', 'email', 'creation_source',
       'last_session_creation_time', 'opted_in_to_mailing_list',
       'enabled_for_marketing_drip', 'org_id', 'invited_by_user_id'],
      dtype='object')

#### One-hot encode creation_source

In [183]:
users_df = users.copy()
users_df.creation_source.value_counts()

creation_source
ORG_INVITE            4254
GUEST_INVITE          2163
PERSONAL_PROJECTS     2111
SIGNUP                2087
SIGNUP_GOOGLE_AUTH    1385
Name: count, dtype: int64

In [184]:
user_creation_source_df = users_df[['object_id', 'creation_source']].drop_duplicates().copy()
user_creation_source_df.rename(columns={'object_id': 'user_id'}, inplace=True)

In [185]:
creation_dummies = pd.get_dummies(user_creation_source_df['creation_source'], prefix='creation', drop_first=True).astype(int)
user_creation_dummies_df = pd.concat([user_creation_source_df[['user_id']], creation_dummies], axis=1)
user_creation_dummies_df.head()

,user_id,creation_ORG_INVITE,creation_PERSONAL_PROJECTS,creation_SIGNUP,creation_SIGNUP_GOOGLE_AUTH
0,1,0,0,0,0
1,2,1,0,0,0
2,3,1,0,0,0
3,4,0,0,0,0
4,5,0,0,0,0

#### Part of an organization flag creation

In [186]:
user_org_flag = users_df[['object_id', 'org_id']].drop_duplicates().copy()
user_org_flag.rename(columns={'object_id': 'user_id'}, inplace=True)

# Binary flag: 1 if org_id not equal to 0, 0 if 0
user_org_flag['part_of_org'] = (user_org_flag['org_id'] != 0).astype(int)

# Keep only user_id and flag
user_org_flag = user_org_flag[['user_id', 'part_of_org']]
user_org_flag.head()

   user_id  part_of_org
0        1            1
1        2            1
2        3            1
3        4            1
4        5            1

In [187]:
user_org_flag['part_of_org'].value_counts(normalize=True)

part_of_org
1    0.973417
0    0.026583
Name: proportion, dtype: float64

#### Invited by user?

In [188]:
user_invited_by_user_flag = users_df[['object_id', 'invited_by_user_id']].drop_duplicates().copy()
user_invited_by_user_flag.rename(columns={'object_id': 'user_id'}, inplace=True)

# Binary flag: 1 if invited_by_user_id exists, 0 if NaN
user_invited_by_user_flag['was_invited'] = user_invited_by_user_flag['invited_by_user_id'].notna().astype(int)

# Keep only user_id and flag
user_invited_by_user_flag = user_invited_by_user_flag[['user_id', 'was_invited']]
user_invited_by_user_flag.head()

   user_id  was_invited
0        1            1
1        2            1
2        3            1
3        4            1
4        5            1

In [189]:
user_invited_by_user_flag['was_invited'].value_counts(normalize=True)

was_invited
1    0.53475
0    0.46525
Name: proportion, dtype: float64

#### Other

In [190]:
other_user_features = ['object_id', 'opted_in_to_mailing_list', 'enabled_for_marketing_drip']
other_user_cols = users_df[other_user_features].copy()
other_user_cols.rename(columns={'object_id': 'user_id'}, inplace=True)
other_user_cols.head()

   user_id  opted_in_to_mailing_list  enabled_for_marketing_drip
0        1                         1                           0
1        2                         0                           0
2        3                         0                           0
3        4                         0                           0
4        5                         0                           0

#### Putting it all together

In [191]:
print("User engagement features\n")
print(active_days_first_14.shape)
print(days_active_before_adoption.shape)
print(days_since_creation_before_adoption.shape)

print("Target feature\n")
print(adopted_flag_df.shape)

print("User info features\n")
print(user_creation_dummies_df.shape)
print(user_org_flag.shape)
print(user_invited_by_user_flag.shape)
print(other_user_cols.shape)

User engagement features

(8822, 2)
(8823, 2)
(8823, 2)
Target feature

(8823, 2)
User info features

(12000, 5)
(12000, 2)
(12000, 2)
(12000, 3)

#### Users with no login sessions
I will impute engagement features with 0 and adopted as 0 for users without any login info

In [192]:
modeling_df = pd.DataFrame({'user_id': users_df['object_id']})

modeling_df = modeling_df.merge(active_days_first_14, on='user_id', how='left')
modeling_df = modeling_df.merge(days_active_before_adoption, on='user_id', how='left')
modeling_df = modeling_df.merge(days_since_creation_before_adoption, on='user_id', how='left')

modeling_df = modeling_df.merge(user_creation_dummies_df, on='user_id', how='left')
modeling_df = modeling_df.merge(user_org_flag, on='user_id', how='left')
modeling_df = modeling_df.merge(user_invited_by_user_flag, on='user_id', how='left')
modeling_df = modeling_df.merge(other_user_cols, on='user_id', how='left')

modeling_df = modeling_df.merge(adopted_flag_df, on='user_id', how='left')

modeling_df.isna().sum()

user_id                                   0
active_days_first_14_days              3178
days_active_before_adoption            3177
days_since_creation_before_adoption    3177
creation_ORG_INVITE                       0
creation_PERSONAL_PROJECTS                0
creation_SIGNUP                           0
creation_SIGNUP_GOOGLE_AUTH               0
part_of_org                               0
was_invited                               0
opted_in_to_mailing_list                  0
enabled_for_marketing_drip                0
adopted                                3177
dtype: int64

In [193]:
# Impute with 0 for missing users
modeling_df['active_days_first_14_days'] = modeling_df['active_days_first_14_days'].fillna(0).astype(int)

# other missing
missing = ['days_active_before_adoption', 'days_since_creation_before_adoption', 'adopted']
modeling_df[missing] = modeling_df[missing].fillna(0).astype(int)
modeling_df.isna().sum()

user_id                                0
active_days_first_14_days              0
days_active_before_adoption            0
days_since_creation_before_adoption    0
creation_ORG_INVITE                    0
creation_PERSONAL_PROJECTS             0
creation_SIGNUP                        0
creation_SIGNUP_GOOGLE_AUTH            0
part_of_org                            0
was_invited                            0
opted_in_to_mailing_list               0
enabled_for_marketing_drip             0
adopted                                0
dtype: int64

In [194]:
# Adopted percentages
modeling_df.adopted.value_counts(normalize=True)

adopted
0    0.8665
1    0.1335
Name: proportion, dtype: float64

### Modelling

In [195]:
# Set user_id as index
modeling_df = modeling_df.set_index('user_id')

# Feature matrix
X = modeling_df.drop(columns='adopted')

# Target
y = modeling_df['adopted']

In [196]:
X.head()

,active_days_first_14_days,days_active_before_adoption,days_since_creation_before_adoption,creation_ORG_INVITE,creation_PERSONAL_PROJECTS,creation_SIGNUP,creation_SIGNUP_GOOGLE_AUTH,part_of_org,was_invited,opted_in_to_mailing_list,enabled_for_marketing_drip
user_id,,,,,,,,,,,
1,1,1,0,0,0,0,0,1,1,1,0
2,1,9,86,1,0,0,0,1,1,0,0
3,1,1,0,1,0,0,0,1,1,0,0
4,1,1,1,0,0,0,0,1,1,0,0
5,1,1,5,0,0,0,0,1,1,0,0

In [197]:
X.describe()

,active_days_first_14_days,days_active_before_adoption,days_since_creation_before_adoption,creation_ORG_INVITE,creation_PERSONAL_PROJECTS,creation_SIGNUP,creation_SIGNUP_GOOGLE_AUTH,part_of_org,was_invited,opted_in_to_mailing_list,enabled_for_marketing_drip
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,0.909083,1.778917,10.627417,0.354500,0.175917,0.173917,0.115417,0.973417,0.534750,0.249500,0.149333
std,0.745451,2.688272,25.233744,0.478381,0.380765,0.379054,0.319537,0.160869,0.498812,0.432742,0.356432
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
75%,1.000000,1.000000,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,5.000000,25.000000,303.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [198]:
# Log transform highly skewed features
X['log_days_active_before_adoption'] = np.log1p(X['days_active_before_adoption'])
X['log_days_since_creation_before_adoption'] = np.log1p(X['days_since_creation_before_adoption'])

In [199]:
# Activity in foirst 14 days can be converted to binary instead of day counts
X['any_activity_first_14'] = (X['active_days_first_14_days'] > 0).astype(int)

In [200]:
# Most users are part of an org, dropping 'part_of_org'
X = X.drop(columns=['part_of_org'])

In [201]:
X = X.drop(columns=['days_active_before_adoption', 'days_since_creation_before_adoption', 'active_days_first_14_days'])
X.head()

,creation_ORG_INVITE,creation_PERSONAL_PROJECTS,creation_SIGNUP,creation_SIGNUP_GOOGLE_AUTH,was_invited,opted_in_to_mailing_list,enabled_for_marketing_drip,log_days_active_before_adoption,log_days_since_creation_before_adoption,any_activity_first_14
user_id,,,,,,,,,,
1,0,0,0,0,1,1,0,0.693147,0.000000,1
2,1,0,0,0,1,0,0,2.302585,4.465908,1
3,1,0,0,0,1,0,0,0.693147,0.000000,1
4,0,0,0,0,1,0,0,0.693147,0.693147,1
5,0,0,0,0,1,0,0,0.693147,1.791759,1

In [202]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [203]:
# Logistic Regression pipeline
# Standardize numeric features
numeric_features = ['log_days_active_before_adoption', 'log_days_since_creation_before_adoption']
categorical_features = [col for col in X.columns if col not in numeric_features]

# highly imbalanced target
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('log_reg', LogisticRegression(
        random_state=42,
        class_weight='balanced',
        max_iter=1000
    ))
])

In [204]:
# Fit model
pipe.fit(X_train, y_train)

# Predict
y_pred = pipe.predict(X_test)
y_proba = pipe.predict_proba(X_test)[:, 1]

# Evaluation
print("Classification Report:\n")
print(classification_report(y_test, y_pred))

roc_auc = roc_auc_score(y_test, y_proba)
print(f"ROC-AUC: {roc_auc}")

Classification Report:

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      2080
           1       0.79      1.00      0.88       320

    accuracy                           0.96      2400
   macro avg       0.90      0.98      0.93      2400
weighted avg       0.97      0.96      0.97      2400

ROC-AUC: 0.9871717247596155

### Data and Features Considered

#### User Engagement Features

- days_active_before_adoption: Total number of days the user was active before adoption (or last session for non-adopters).

- days_since_creation_before_adoption: Time from account creation to adoption (or last session for non-adopters).

- any_activity_first_14: Whether the user had any activity in the first 14 days.

#### User Info / Metadata Flags

- Creation source (e.g., ORG_INVITE, PERSONAL_PROJECTS, SIGNUP, SIGNUP_GOOGLE_AUTH).

- Marketing flags (enabled_for_marketing_drip, opted_in_to_mailing_list).

- Invitation status (was_invited).

Note: Features like sessions_first_14_days were initially considered but dropped to avoid redundancy. I preferred to only keep 'days_active_before_adoption' which is the same as 'sessions_first_14_days'(no multiple logins per day).

#### Methodology

Data was aggregated at the user level, ensuring features only included activity up to the adoption date to prevent leakage.

Logistic regression was used as a simple, interpretable model.

Feature coefficients were analyzed to determine their predictive strength and directionality.

In [206]:
# Get coefficients from the trained logistic regression
coef = pipe.named_steps['log_reg'].coef_[0]

feature_importance = pd.DataFrame({
    'feature': X.columns,
    'coefficient': coef
})

# Sort by absolute value to see most predictive features
feature_importance['abs_coeff'] = feature_importance['coefficient'].abs()
feature_importance = feature_importance.sort_values(by='abs_coeff', ascending=False)

print(feature_importance[['feature', 'coefficient']])

                                   feature  coefficient
7          log_days_active_before_adoption     6.924484
8  log_days_since_creation_before_adoption    -2.043243
9                    any_activity_first_14    -0.342311
6               enabled_for_marketing_drip    -0.114111
5                 opted_in_to_mailing_list     0.069843
0                      creation_ORG_INVITE    -0.067012
1               creation_PERSONAL_PROJECTS    -0.040812
4                              was_invited     0.020347
2                          creation_SIGNUP     0.011701
3              creation_SIGNUP_GOOGLE_AUTH     0.002946

### Observations
- Users who are more active early in their account’s life are far more likely to adopt the product.
- The longer it takes a user to adopt after signing up, the less likely they are to do so.
- Other factors, like how the user signed up, whether they were invited, or marketing indicators, have very little impact compared to early activity.

Early engagement is the strongest predictor of future adoption.

#### Further Considerations

- Adoption timing patterns
  
Explore whether users adopt in bursts of activity versus steady engagement. For example, do a few highly active days early predict adoption more than many low-activity days?

- Cross-feature interactions

Investigate whether certain combinations of flags and engagement metrics amplify adoption likelihood. For instance, does being invited and active in the first week increase adoption disproportionately?

- Adoption horizon

Adoption was defined relative to each user, resulting in inconsistent horizons. Using a standardized window across users could improve comparability and clarity of the analysis.